[package]
name = "voj-host"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
guest = { path = "../guest", package = "voj-guest" }
ark-serialize = { workspace = true }
spinners = { workspace = true }

[features]
icicle = ["jolt-sdk/icicle"]
