[target.riscv64gc-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture riscv64",
    """tee /etc/apt/sources.list.d/ubuntu.sources <<EOF
Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports noble-security
Components: main universe restricted multiverse
Architectures: amd64
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://ports.ubuntu.com/ubuntu-ports/
Suites: noble noble-updates noble-backports noble-security
Components: main universe restricted multiverse
Architectures: arm64 riscv64
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF""",
    "apt-get update",
    "apt-get install -y libssl-dev:riscv64",
] 

[target.riscv64gc-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-self-contained=yes", "-C", "link-arg=-static"]

pre-build = [
    "dpkg --add-architecture riscv64",
    """tee /etc/apt/sources.list.d/ubuntu.sources <<EOF
Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports noble-security
Components: main universe restricted multiverse
Architectures: amd64
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://ports.ubuntu.com/ubuntu-ports/
Suites: noble noble-updates noble-backports noble-security
Components: main universe restricted multiverse
Architectures: arm64 riscv64
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF""",
    "apt-get update",
] 