[target.riscv64gc-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture riscv64",
    "echo 'deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports bonic main universe' >> /etc/apt/sources.list",
    "echo 'deb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports bonic-updates main universe' >> /etc/apt/sources.list",
    "apt-get update",
    "apt-get install -y libssl-dev:riscv64",
] 