[package]
name = "fib-host"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
fib-guest = { workspace = true }
ark-serialize = { workspace = true }
spinners = { workspace = true }

[features]
icicle = ["jolt-sdk/icicle"]
